// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opjrhfdpjrvrbiagwovx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wanJoZmRwanJ2cmJpYWd3b3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNTk4ODksImV4cCI6MjA1NDczNTg4OX0.TETSQs3ij5SEMRCVisnko1XMmeQF573R7C0lbnPLQQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);